name: Build and Scan Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/cicd:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/cicd:latest

  sonarqube-scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2.0.0
        with:
          args: >
            -Dsonar.projectKey=my-project
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
